[package]
name = "pair_count"
version = "0.0.1"

[[bin]]
name = "main"
path = "src/main/rust/main.rs"

[dependencies]
clap = { version = "3.0.14", features = ["derive"] }
csv = "1.1"
itertools = "0.10.2"
noodles = { version = "0.20.0", features = ["bam","sam"] }

