[package]
name = "pair_count"
version = "0.0.1"

[[bin]]
name = "crispr-rust"
path = "src/main/rust/main.rs"

[dependencies]
clap = { version = "3.0.14", features = ["derive"] }
csv = "1.1"
itertools = "0.10.2"
rust-htslib = "0.38.2"

